### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by tune6688** [LigeroSmart/ligerosmart-easyinstall#1]
Hello Writer
My system is centos-release-7-9.2009.1.el7.centos.x86_64 and used this " curl https://get.ligerosmart.com | sh "command to install the ligerosmart failure. Can you hellp me? Thanks!
Error  message as below
"Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ap8zognz/cryptography/
The elasticsearch service will not run with max_map_count=65530. I will try to increase it
vm.max_map_count = 262144
Cloning into 'ligerosmart-stack'...
remote: Enumerating objects: 121, done.
remote: Counting objects: 100% (121/121), done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 121 (delta 75), reused 105 (delta 65), pack-reused 0
Receiving objects: 100% (121/121), 15.86 KiB | 0 bytes/s, done.
Resolving deltas: 100% (75/75), done.
Docker version 20.10.3, build 48d30b5
sh: line 70: docker-compose: command not found
sh: line 73: docker-compose: command not found
sh: line 76: docker-compose: command not found".

**Comment by mfmatos** [comment]
Hello,

This appears to be some conflict with the version of python on your system.

What version of python and pip? 

`pip --version && python --version`

**Comment by mfmatos** [comment]
Try with command above:

`curl https://get.ligerosmart.com | sudo sh`

It's works?

**Comment by mfmatos** [comment]
Try to upgrade pip:

`python3 -m pip install --upgrade pip`

It's works?

**Comment by tune6688** [comment]
You fixed it,thank you very much!
