### ISSUE TITLE
Erro na instalação

### ISSUE THREAD

**Issue by Geidiam** [LigeroSmart/ligerosmart-easyinstall#3]
Sempre aparece esse erro quando tento instalar:

Name                   Command           State           Ports
--------------------------------------------------------------------------------
ligerosmart-             docker-entrypoint.sh     Up      3306/tcp, 33060/tcp
stack_database_1         --max ...
ligerosmart-             /usr/local/bin/docker-   Up      9200/tcp, 9300/tcp
stack_elasticsearch_1    entr ...
ligerosmart-             /run.sh                  Up      3000/tcp
stack_grafana_1
ligerosmart-             /traefik --docker        Up      0.0.0.0:443->443/tcp,:
stack_ingress_1          --docker ...                     ::443->443/tcp, 0.0.0.
                                                          0:80->80/tcp,:::80->80
                                                          /tcp
ligerosmart-             /bin/bash c /app       Up      80/tcp
stack_web_1              run.sh

**Comment by mfmatos** [comment]
Olá @Geidiam ,

Nessas linhas estão sendo mostrados os status dos serviços, e no caso mostra que estão rodando. Para continuar você deve acessar seu servidor com um navegador na porta 80 para acessar a interface web.

Mais alguma dúvida?

**Comment by mfmatos** [comment]
Olá @Geidiam , conseguiu acessar o sistema? Nossa documentação pode ajudar também

https://docs.ligerosmart.org/

**Comment by Geidiam** [comment]
Consegui sim, deu tudo certo, muito obrigado pelo suporte prestativo

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
